Adds download and return dfs function (principle+supplimentary)
GSS-Cogs/gss-utils pull request #146
Opened 2021-01-15 17:21 UTC by CharlesRendle

Not tested. Have a few questions:
1) Where should the imports go? I added all 4 in the same 2nd block (lines 11-14)
2) Where does the session management and caching belong? I haven't included it in this commit.
3) If periods_wanted is a list, should `get_principle_dataframes` return a dictionary of dataframes where key = period?

I have changed `get_supplimentary_dfs` to return the whole dictionary.

2021-01-18 22:32 UTC, mikeAdamss commented
@CharlesRendle - quick comments while im here.

1. imports should be split into 3 blocks separated by spaces: (a) imports from the standard library (b) other peoples modules, i.e anything youd need to pip install (c) local modules, i.e anything from another part of gssutils in this case.

2. as long as you use session.get i think it'd go elsewhere (probably, id go on that assumption until we wire it together).

3. no, concatenate them all to a single df and return that, we've already declared we want all those periods.

2021-01-21 10:31 UTC, canwaf requested changes

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
> +    if len(periods_wanted) != 0:
is None:

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
>      Given a distribution object and a list of periods of data we want
periods_wanted: list = None

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
> +        principle_df = _get_odata_data(url) # TODO - dont forget we're returning a blank dataframe here!
Remove todo

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
> +            df_list.append(_get_odata_data(url))
`pd.merge([df1,df2])` can replace the list append and concat out of the for loop

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
> +    #return {'key', pd.DataFrame}
Remove comment.

2021-01-21 10:31 UTC, canwaf commented on gssutils/metadata/dcat.py
> +
Add backoff decorator

2021-01-21 15:49 UTC, CharlesRendle commented on gssutils/metadata/dcat.py
> +            principle_df = principle_df.append(_get_odata_data(url))
Using `.append` instead of `.merge` to achieve the same goal of eliminating the need to create a list of dataframes.

2021-01-25 08:52 UTC, merged

2021-01-25 08:53 UTC, canwaf approved these changes