allow mapping of attribute with or without value & scenario's to chec…
GSS-Cogs/gss-utils pull request #270
Opened 2021-06-03 16:43 UTC by Shannon95

…k outcomes are valid.

2021-06-04 08:40 UTC, canwaf requested changes
We need to be more intentional with our fixtures, instead of using the files in whatever edge case work we need to make work. Can @rossbowen make synthetic data and metadata to focus the test case on this specific thing?

2021-06-04 08:40 UTC, canwaf commented on features/fixtures/business-characteristics-data-tables.csv
> +24187818088,imports,year/2019,BE,B5,all,all,all,5170.0,4344200.0,
Test a subset, not the entire fixture. Do we need this full CSV?

2021-06-09 14:07 UTC, rossbowen commented on features/csvw.feature
> +        <http://gss-data.org.uk/def/trade/property/attribute/business-count> "5170.0";
I'm noticing that numerics are being output as strings (which is the default behaviour - `csv2rdf` will treat things as strings unless told otherwise.

It's an extra ask, but I wonder if we should do something like this, but for attributes, so a user can explicitly state something is a number if they so wish. 

https://github.com/GSS-Cogs/gss-utils/blob/master/gssutils/csvw/mapping.py#L352-L353

2021-06-29 14:19 UTC, Shannon95 commented on features/csvw.feature
> +        <http://gss-data.org.uk/def/trade/property/attribute/business-count> "5170.0";
Users can now explicitly state something is a number within the mapping if required.

2021-06-29 15:15 UTC, rossbowen approved these changes

2021-07-05 09:27 UTC, merged