Csvcubed datatypes
GSS-Cogs/gss-utils pull request #366
Opened 2022-08-12 13:13 UTC by mikeAdamss

Integrates the datatype setting functionality we're adding to csvcubed into our gssutils tooling.

NOTE - dependent on **merge AND release** of https://github.com/GSS-Cogs/csvcubed/pull/558.

Will need to update to that released version of csvcubed when we do as well, bump in poetry etc.

2022-08-12 13:14 UTC, mikeAdamss commented
@robons - up for a PR when you get time, obviously wont merge anything until the csvcubed bits are in and all tests pass.

2022-08-23 08:59 UTC, robons commented on csvcubedintegrationfeatures/steps/infojson.py
> -    errors += validate_qb_component_constraints(context.cube)
I believe we still need to call both of these functions you've removed. They should get added to any `validation_errors` from the previous step definition.

2022-08-23 08:59 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +    dtype = datatypes.get_pandas_datatypes(data_path, config=config)
This function shouldn't work with the info.json v1.1 syntax files. It applies the logic of the qube-config.json and we need a similar function defined for info.json v1.1 files.

2022-08-25 08:54 UTC, robons commented on csvcubedintegrationfeatures/steps/infojson.py
>      errors = cube.validate()
These errors need to be concatenated with the others too.

2022-08-25 09:00 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +) -> Tuple[Dict[str, str], List[CsvColumn]]:
I think your types are the wrong way around in here.

2022-08-25 09:00 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +    data = pd.read_csv(data_path)
Do we need to read the whole CSV. Can we limit it to 1 or 2 lines just to get the headers?

2022-08-25 09:08 UTC, robons commented on Dockerfile
> +RUN ${VENV_PIP} uninstall cachecontrol -y
It might be worth removing `--without-hashes` on line 24 to see whether that gives the requirements.txt enough of a constraint to install the appropriate version. I can't remember exactly why I included `--without-hashes` there; I remember the build was failing with it, but I have a suspicion that it was because we were installing packages directly from github repos (which we aren't anymore). May be worth a try.

2022-08-25 09:09 UTC, robons approved these changes
Just one or two minor things to consider, but seems to be pretty much there. Good work.

2022-08-31 10:27 UTC, mikeAdamss commented on Dockerfile
> +RUN ${VENV_PIP} uninstall cachecontrol -y
Worth a go but no can do, we've still got databaker from github in the mix.

Our version of databaker is such a gigantic bag of hacks right now that I don't see any way of merging that to push up to the official databaker pypi any time soon (its got packages in there that were depreciated in 2016, it works for us, but mainly as I've twisted it to our specific use case of new pandas and new python).

Basically, needs replacing and we don't have 6 months to spend on a tool for flattening spreadsheets we ultimately don't want..... just gotta hope it doesn't implode at some point before we stop using it I think.

2022-09-05 07:01 UTC, mikeAdamss commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +    data = pd.read_csv(data_path)
@robons - great question - this ended up opening a whole (necessary) barrel of worms on me - TLDR is I was (a) reading in the csv to get the QbColumns and then (b) using the data types to reading in the obs data.

but - that first read for QbColumns was also creating the codelists (I didn't realise originally), so allowed a scenario of pandas "best guess" typed codelists with correctly typed obs columns.

had to pull it apart hard to get the behaviour we want, tests pass but wanted to wait on a sanity check/re-review before I release as I had to change a lot.

would probably benefit from maybe a class and not having to repeat setting the `maybe_x` variables, but its internal glue code and I'm a fair bit overdue looking at other things so didn't go down that road.

2022-09-07 08:23 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +from unittest.mock import NonCallableMagicMock
Do we need this here?

2022-09-07 08:40 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +    1.) Get the column titles only from the csv
I don't think we actually need the column titles at all. We're not doing conventional column configuration in gss-utils.

2022-09-07 08:45 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +    # raise Exception(column_schemas)
remove

2022-09-07 08:52 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +) -> schema.SchemaBaseClass:
I think the valid type signature is `Type[schema.SchemaBaseClass]` since you're passing around a type rather than in instance of `schema.SchemaBaseClass`.

2022-09-07 08:54 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +            dtype_str = column_schema["data_type"]
Given that your're actually holding a `Dict[str, Type[schema.SchemaBaseClass]]`, the column schema is never actually an instance of `schema.SchemaBaseClass` and so you'll never be able to get the `data_type` field off it.

2022-09-07 09:00 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson1point1/mapcolumntocomponent.py
>  ) -> Union[
Again, this is really `Union[Type[schema.NewDimension], Type[...], ...]`.

2022-09-07 09:03 UTC, robons requested changes
I don't understand how you behaviour test is passing, but I don't think you're actually loading the attribute/obsval columns' data types.

2022-09-08 13:20 UTC, mikeAdamss commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +from unittest.mock import NonCallableMagicMock
sorry, didn't push my tidy up commit, that was silly.

2022-09-09 10:12 UTC, mikeAdamss commented
Good spots, should be better now, have also tidied up the logic (a bit) to make it a little easier to follow. Updated the dependencies as dependabot is moaning.

Unexpected BDD passing was because I was using ideal data (pandas best guess happened to return the correct results), should have started from a failed test. Have altered the test data dims to have leading zeroes, should blow up now if the the datatype functionality fails.

2022-09-09 11:13 UTC, mikeAdamss commented
Test was passing as I gave it perfect test data (so pandas "best guess" was right). Have updated to include some nice leading 0 dimensions.

Addressed pr comments, tidy up logic (a bit) and updated deps.

2022-09-09 13:53 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson1point1/columnschema.py
> +    name: str
I'd call this `title` for consistency.

2022-09-09 13:54 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson1point1/columnschema.py
> +    schema_type: Optional[Union[Type[SchemaBaseClass], Dict]] = None
This can also be expressed as `Union[Type[SchemaBaseClass], Dict, None]`.

2022-09-09 13:57 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson1point1/columnschema.py
> +    def with_column_schema(self) -> InfoForColumn:
I'd be tempted to put set `schema_type: Union[...] = field(init=False)` at the top and put this logic in a `__post_init__` function which will automatically get called after init - you can then populate the schema_type field directly. Unless the copy functionality is truly necessary?

2022-09-09 14:17 UTC, robons approved these changes
I sincerely hope I never have to look at this code again.

2022-09-09 14:17 UTC, robons commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +        if column_info.schema_type is schema.ObservationValue:
The data_type should default to `decimal` for both ObservationValue columns as well as AttributeLiteral columns too.

2022-09-12 10:50 UTC, mikeAdamss commented on gssutils/csvcubedintegration/configloaders/infojson.py
> +        if column_info.schema_type is schema.ObservationValue:
As far as I can tell we've only ever create literals when `literalValuesDataType` is not None. As such have added some logic to catch that data type field but haven't added a default, I don't think it'd ever play (if it ain't specified, it ain't a literal, in gssutils land anyway).

There's a case for pulling apart all this implict stuff like we did in csvcubed configloader but (a) its glue code and (b) I'm _waaaaaaaaay_ overdue on my urgent switch of focus, if it needs doing it can't be me.

2022-09-12 14:46 UTC, merged