Issue 90
GSS-Cogs/gss-utils pull request #91
Opened 2020-09-30 18:55 UTC by mikeAdamss

PR for updating the csvw/csv/trig writing functionality of the cubes class ready for use in production as detailed here: https://github.com/GSS-Cogs/gss-utils/issues/90

## What is the Cubes Class?

The Cubes() class was an early iteration of a class to encapulsate the dataframe, the csvw and the trig (metadata) file representing a single dataset as output by a pipeline. It was also built to generate codelists and their accompanying csvw schemas.

We got it to an MVP version but additional compexities around how to structure csvw outputs needed to be worked out so it hasn't been in use. The DMs have nailed down what they want in the way of csvw's so this PR is to:

* Updates the csvw,csv,trig generation to match the current outputs required.
* Minimise the code footprint in the transforms, i.e "pull stuff out".
* Flags off the codelist generation functionality (for now) so we can use the csvw bit.
* Update the Cubes() tests to work with the updated functionality.

## How to review?

1.) Run the tests - within a locally cloned gssutils repo
`pipenv sync`
`pipenv install -r test-requirements.txt`
`pipenv run behave -D record_mode=none --tags=-skip features/cubes.feature`

2.) Sanity check the code alterations.

2020-10-07 14:32 UTC, cadmiumcat requested changes
Tests passed 👍 
Added a couple of comments

2020-10-08 11:30 UTC, mikeAdamss commented on gssutils/scrape.py
> +                self.dataset.family = pathify(self.seed["families"][0])
I'm not sure either tbh, but I'm using rather than defining here (the 'families' field is from the info.json and is being pulled through from airtable). I'd guess there is/will be a bit of work to register a dataset in more than 1 family at some point, we're not there yet though.

2020-10-08 11:39 UTC, cadmiumcat commented on gssutils/scrape.py
> +                self.dataset.family = pathify(self.seed["families"][0])
in that case, should we go for `self.dataset.families`?

2020-10-08 20:02 UTC, mikeAdamss commented on gssutils/scrape.py
> +                self.dataset.family = pathify(self.seed["families"][0])
The `self.seed["families"][0]` bit is taking the 1st "families" value and putting it in self.dataset.family (which only stores 1 family value because that's all the csvw generation code handles).

So I see where you're coming from but I think it will have to wait until/if we support registering more than one family, otherwise we end up with a strictly single value field that implies multiple values.

2020-10-09 08:59 UTC, ajtucker commented on gssutils/scrape.py
> +                self.dataset.family = pathify(self.seed["families"][0])
It's my fault for not being explicit about how these metadata fields work, but when they get converted to RDF, there can be multiple RDF statements with the same subject (in this case `pmdcat:Dataset` (a subclass of `dcat:Dataset`)), same predicate (in this case `gdp:family`) but different objects (in this case, the different families). To allow for a single metadata field being able to have zero, one or many values, the Python values are coerced into a list if they're not already a list type and then serialised out as zero, one or many RDF statements.

The upshot is that you should be able to assign a list of families to `self.dataset.family`.

2020-10-09 10:05 UTC, cadmiumcat commented on gssutils/scrape.py
> +                self.dataset.family = pathify(self.seed["families"][0])
ok, if I understand correctly, it sounds like `self.dataset.families` would make more sense

But I get the feeling maybe I don't understand correctly 😆, so please don't let me stop you 😁 .

2020-10-09 10:07 UTC, cadmiumcat approved these changes
As far as I can tell, this won't break things 😁

2020-10-09 13:54 UTC, merged

2020-10-09 15:32 UTC, ajtucker commented
We may need to revert this and check all the tests pass, not just the `cubes.feature ones`, though not last thing on a Friday!

There seems to be a logic error in moving the `_override_metadata_where_specified()` call in https://github.com/GSS-Cogs/gss-utils/pull/91/files/f92319ee2c3e6fc093e6f03142a498f9546097f8#diff-edd08a6cfef2f165278eea5227f43db2L155 outside of the check for whether there's a seed file, as the function goes off and uses values from the seed file.